# Site
repository: linzhiqiu/linzhiqiu.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Zhiqiu Lin
title: Undergraduate Researcher
email: zl279@cornell.edu
phone: 
website: linzhiqiu.github.io

# Social links
# github_username:  linzhiqiu
# linkedin_username: Zhiqiu Lin

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg # Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Hi, I am an undergradute researcher at Cornell University.
  
  I work at the intersection of **computer vision** and **machine learning**, aiming to build efficient learning systems that can reveal intriguing facets of our world.
  
  I do <mark>photography</mark> and <mark>unicycling</mark>!

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I do <mark>photography</mark> and <mark>unicycling</mark>!

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
